name: Deploy Laravel App

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Change this to your PHP version


    - name:  Composer Update
      run: composer update --lock

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Build assets (if applicable)
      run: |
        npm install
        npm run production  # or any other build script

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: .  # Deploy the entire project directory
        remote-dir: /home/demospv/axionadmin
